# Fork from https://github.com/simonsmh/notocjk/blob/master/customize.sh
[ -x "$(which magisk)" ] && MIRRORPATH=$(magisk --path)/.magisk/mirror || unset MIRRORPATH
FILES="fonts.xml fonts_base.xml"
FILEPATH=/system/etc/
FONTPATH=/system/fonts/
MINSDK=26
MINVER="8.0(Oreo)"
SANSNAME=NotoSansCJK-VF-Android.otf.ttc
SERIFNAME=NotoSerifCJK-VF-Android.otf.ttc
TIMES=0

for FILE in $FILES
do
    if [ "$API" -ge "$MINSDK" ] && [ -f $MIRRORPATH$FILEPATH$FILE ]; then
        TIMES=$((TIMES+1))

        ui_print "- Migrating $FILE"
        mkdir -p $MODPATH$FILEPATH
        cp -af $MIRRORPATH$FILEPATH$FILE $MODPATH$FILEPATH$FILE
        
        if [ "$API" -ge "31" ]; then
            # https://issuetracker.google.com/issues/204644136
            sed -i '
            /<family lang=\"zh-Hans\">/,/<\/family>/ {:a;N;/<\/family>/!ba;
            s/<family lang=\"zh-Hans\">.*Noto.*CJK.*<\/family>/<family lang="zh-Hans">\n        <font weight="100" style="normal" index="2" postScriptName="NotoSansCJKjp-Thin">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="100.0" \/>\n        <\/font>\n        <font weight="300" style="normal" index="2" postScriptName="NotoSansCJKjp-Thin">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="300.0" \/>\n        <\/font>\n        <font weight="350" style="normal" index="2" postScriptName="NotoSansCJKjp-Thin">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="350.0" \/>\n        <\/font>\n        <font weight="400" style="normal" index="2" postScriptName="NotoSansCJKjp-Thin">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="400.0" \/>\n        <\/font>\n        <font weight="500" style="normal" index="2" postScriptName="NotoSansCJKjp-Thin">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="500.0" \/>\n        <\/font>\n        <font weight="700" style="normal" index="2" postScriptName="NotoSansCJKjp-Thin">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="700.0" \/>\n        <\/font>\n        <font weight="900" style="normal" index="2" postScriptName="NotoSansCJKjp-Thin">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="900.0" \/>\n        <\/font>\n\n        <font weight="200" style="normal" index="2" fallbackFor="serif" postScriptName="NotoSerifCJKjp-ExtraLight">NotoSerifCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="200.0" \/>\n        <\/font>\n        <font weight="300" style="normal" index="2" fallbackFor="serif" postScriptName="NotoSerifCJKjp-ExtraLight">NotoSerifCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="300.0" \/>\n        <\/font>\n        <font weight="400" style="normal" index="2" fallbackFor="serif" postScriptName="NotoSerifCJKjp-ExtraLight">NotoSerifCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="400.0" \/>\n        <\/font>\n        <font weight="500" style="normal" index="2" fallbackFor="serif" postScriptName="NotoSerifCJKjp-ExtraLight">NotoSerifCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="500.0" \/>\n        <\/font>\n        <font weight="600" style="normal" index="2" fallbackFor="serif" postScriptName="NotoSerifCJKjp-ExtraLight">NotoSerifCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="600.0" \/>\n        <\/font>\n        <font weight="700" style="normal" index="2" fallbackFor="serif" postScriptName="NotoSerifCJKjp-ExtraLight">NotoSerifCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="700.0" \/>\n        <\/font>\n        <font weight="900" style="normal" index="2" fallbackFor="serif" postScriptName="NotoSerifCJKjp-ExtraLight">NotoSerifCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="900.0" \/>\n        <\/font>\n    <\/family>/};
            ' $MODPATH$FILEPATH$FILE

            sed -i '
            /<family lang=\"zh-Hant\">/,/<\/family>/ {:a;N;/<\/family>/!ba;
            s/<family lang=\"zh-Hant\">.*Noto.*CJK.*<\/family>/<family lang="zh-Hant">\n        <font weight="100" style="normal" index="3" postScriptName="NotoSansCJKjp-Thin">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="100.0" \/>\n        <\/font>\n        <font weight="300" style="normal" index="3" postScriptName="NotoSansCJKjp-Thin">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="300.0" \/>\n        <\/font>\n        <font weight="350" style="normal" index="3" postScriptName="NotoSansCJKjp-Thin">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="350.0" \/>\n        <\/font>\n        <font weight="400" style="normal" index="3" postScriptName="NotoSansCJKjp-Thin">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="400.0" \/>\n        <\/font>\n        <font weight="500" style="normal" index="3" postScriptName="NotoSansCJKjp-Thin">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="500.0" \/>\n        <\/font>\n        <font weight="700" style="normal" index="3" postScriptName="NotoSansCJKjp-Thin">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="700.0" \/>\n        <\/font>\n        <font weight="900" style="normal" index="3" postScriptName="NotoSansCJKjp-Thin">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="900.0" \/>\n        <\/font>\n\n        <font weight="200" style="normal" index="3" fallbackFor="serif" postScriptName="NotoSerifCJKjp-ExtraLight">NotoSerifCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="200.0" \/>\n        <\/font>\n        <font weight="300" style="normal" index="3" fallbackFor="serif" postScriptName="NotoSerifCJKjp-ExtraLight">NotoSerifCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="300.0" \/>\n        <\/font>\n        <font weight="400" style="normal" index="3" fallbackFor="serif" postScriptName="NotoSerifCJKjp-ExtraLight">NotoSerifCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="400.0" \/>\n        <\/font>\n        <font weight="500" style="normal" index="3" fallbackFor="serif" postScriptName="NotoSerifCJKjp-ExtraLight">NotoSerifCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="500.0" \/>\n        <\/font>\n        <font weight="600" style="normal" index="3" fallbackFor="serif" postScriptName="NotoSerifCJKjp-ExtraLight">NotoSerifCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="600.0" \/>\n        <\/font>\n        <font weight="700" style="normal" index="3" fallbackFor="serif" postScriptName="NotoSerifCJKjp-ExtraLight">NotoSerifCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="700.0" \/>\n        <\/font>\n        <font weight="900" style="normal" index="3" fallbackFor="serif" postScriptName="NotoSerifCJKjp-ExtraLight">NotoSerifCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="900.0" \/>\n        <\/font>\n    <\/family>/};
            ' $MODPATH$FILEPATH$FILE

            sed -i '
            /<family lang=\"zh-Bopo\">/,/<\/family>/ {:a;N;/<\/family>/!ba;
            s/<family lang=\"zh-Bopo\">.*Noto.*CJK.*<\/family>/<family lang="zh-Bopo">\n        <font weight="100" style="normal" index="3" postScriptName="NotoSansCJKjp-Thin">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="100.0" \/>\n        <\/font>\n        <font weight="300" style="normal" index="3" postScriptName="NotoSansCJKjp-Thin">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="300.0" \/>\n        <\/font>\n        <font weight="350" style="normal" index="3" postScriptName="NotoSansCJKjp-Thin">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="350.0" \/>\n        <\/font>\n        <font weight="400" style="normal" index="3" postScriptName="NotoSansCJKjp-Thin">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="400.0" \/>\n        <\/font>\n        <font weight="500" style="normal" index="3" postScriptName="NotoSansCJKjp-Thin">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="500.0" \/>\n        <\/font>\n        <font weight="700" style="normal" index="3" postScriptName="NotoSansCJKjp-Thin">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="700.0" \/>\n        <\/font>\n        <font weight="900" style="normal" index="3" postScriptName="NotoSansCJKjp-Thin">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="900.0" \/>\n        <\/font>\n\n        <font weight="200" style="normal" index="3" fallbackFor="serif" postScriptName="NotoSerifCJKjp-ExtraLight">NotoSerifCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="200.0" \/>\n        <\/font>\n        <font weight="300" style="normal" index="3" fallbackFor="serif" postScriptName="NotoSerifCJKjp-ExtraLight">NotoSerifCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="300.0" \/>\n        <\/font>\n        <font weight="400" style="normal" index="3" fallbackFor="serif" postScriptName="NotoSerifCJKjp-ExtraLight">NotoSerifCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="400.0" \/>\n        <\/font>\n        <font weight="500" style="normal" index="3" fallbackFor="serif" postScriptName="NotoSerifCJKjp-ExtraLight">NotoSerifCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="500.0" \/>\n        <\/font>\n        <font weight="600" style="normal" index="3" fallbackFor="serif" postScriptName="NotoSerifCJKjp-ExtraLight">NotoSerifCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="600.0" \/>\n        <\/font>\n        <font weight="700" style="normal" index="3" fallbackFor="serif" postScriptName="NotoSerifCJKjp-ExtraLight">NotoSerifCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="700.0" \/>\n        <\/font>\n        <font weight="900" style="normal" index="3" fallbackFor="serif" postScriptName="NotoSerifCJKjp-ExtraLight">NotoSerifCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="900.0" \/>\n        <\/font>\n    <\/family>/};
            ' $MODPATH$FILEPATH$FILE

            sed -i '
            /<family lang=\"zh-Hant zh-Bopo\">/,/<\/family>/ {:a;N;/<\/family>/!ba;
            s/<family lang=\"zh-Hant zh-Bopo\">.*Noto.*CJK.*<\/family>/<family lang="zh-Hant zh-Bopo">\n        <font weight="100" style="normal" index="3" postScriptName="NotoSansCJKjp-Thin">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="100.0" \/>\n        <\/font>\n        <font weight="300" style="normal" index="3" postScriptName="NotoSansCJKjp-Thin">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="300.0" \/>\n        <\/font>\n        <font weight="350" style="normal" index="3" postScriptName="NotoSansCJKjp-Thin">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="350.0" \/>\n        <\/font>\n        <font weight="400" style="normal" index="3" postScriptName="NotoSansCJKjp-Thin">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="400.0" \/>\n        <\/font>\n        <font weight="500" style="normal" index="3" postScriptName="NotoSansCJKjp-Thin">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="500.0" \/>\n        <\/font>\n        <font weight="700" style="normal" index="3" postScriptName="NotoSansCJKjp-Thin">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="700.0" \/>\n        <\/font>\n        <font weight="900" style="normal" index="3" postScriptName="NotoSansCJKjp-Thin">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="900.0" \/>\n        <\/font>\n\n        <font weight="200" style="normal" index="3" fallbackFor="serif" postScriptName="NotoSerifCJKjp-ExtraLight">NotoSerifCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="200.0" \/>\n        <\/font>\n        <font weight="300" style="normal" index="3" fallbackFor="serif" postScriptName="NotoSerifCJKjp-ExtraLight">NotoSerifCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="300.0" \/>\n        <\/font>\n        <font weight="400" style="normal" index="3" fallbackFor="serif" postScriptName="NotoSerifCJKjp-ExtraLight">NotoSerifCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="400.0" \/>\n        <\/font>\n        <font weight="500" style="normal" index="3" fallbackFor="serif" postScriptName="NotoSerifCJKjp-ExtraLight">NotoSerifCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="500.0" \/>\n        <\/font>\n        <font weight="600" style="normal" index="3" fallbackFor="serif" postScriptName="NotoSerifCJKjp-ExtraLight">NotoSerifCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="600.0" \/>\n        <\/font>\n        <font weight="700" style="normal" index="3" fallbackFor="serif" postScriptName="NotoSerifCJKjp-ExtraLight">NotoSerifCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="700.0" \/>\n        <\/font>\n        <font weight="900" style="normal" index="3" fallbackFor="serif" postScriptName="NotoSerifCJKjp-ExtraLight">NotoSerifCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="900.0" \/>\n        <\/font>\n    <\/family>/};
            ' $MODPATH$FILEPATH$FILE

            sed -i '
            /<family lang=\"zh-Hant,zh-Bopo\">/,/<\/family>/ {:a;N;/<\/family>/!ba;
            s/<family lang=\"zh-Hant,zh-Bopo\">.*Noto.*CJK.*<\/family>/<family lang="zh-Hant,zh-Bopo">\n        <font weight="100" style="normal" index="3" postScriptName="NotoSansCJKjp-Thin">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="100.0" \/>\n        <\/font>\n        <font weight="300" style="normal" index="3" postScriptName="NotoSansCJKjp-Thin">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="300.0" \/>\n        <\/font>\n        <font weight="350" style="normal" index="3" postScriptName="NotoSansCJKjp-Thin">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="350.0" \/>\n        <\/font>\n        <font weight="400" style="normal" index="3" postScriptName="NotoSansCJKjp-Thin">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="400.0" \/>\n        <\/font>\n        <font weight="500" style="normal" index="3" postScriptName="NotoSansCJKjp-Thin">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="500.0" \/>\n        <\/font>\n        <font weight="700" style="normal" index="3" postScriptName="NotoSansCJKjp-Thin">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="700.0" \/>\n        <\/font>\n        <font weight="900" style="normal" index="3" postScriptName="NotoSansCJKjp-Thin">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="900.0" \/>\n        <\/font>\n\n        <font weight="200" style="normal" index="3" fallbackFor="serif" postScriptName="NotoSerifCJKjp-ExtraLight">NotoSerifCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="200.0" \/>\n        <\/font>\n        <font weight="300" style="normal" index="3" fallbackFor="serif" postScriptName="NotoSerifCJKjp-ExtraLight">NotoSerifCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="300.0" \/>\n        <\/font>\n        <font weight="400" style="normal" index="3" fallbackFor="serif" postScriptName="NotoSerifCJKjp-ExtraLight">NotoSerifCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="400.0" \/>\n        <\/font>\n        <font weight="500" style="normal" index="3" fallbackFor="serif" postScriptName="NotoSerifCJKjp-ExtraLight">NotoSerifCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="500.0" \/>\n        <\/font>\n        <font weight="600" style="normal" index="3" fallbackFor="serif" postScriptName="NotoSerifCJKjp-ExtraLight">NotoSerifCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="600.0" \/>\n        <\/font>\n        <font weight="700" style="normal" index="3" fallbackFor="serif" postScriptName="NotoSerifCJKjp-ExtraLight">NotoSerifCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="700.0" \/>\n        <\/font>\n        <font weight="900" style="normal" index="3" fallbackFor="serif" postScriptName="NotoSerifCJKjp-ExtraLight">NotoSerifCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="900.0" \/>\n        <\/font>\n    <\/family>/};
            ' $MODPATH$FILEPATH$FILE

            sed -i '
            /<family lang=\"ja\">/,/<\/family>/ {:a;N;/<\/family>/!ba;
            s/<family lang=\"ja\">.*Noto.*CJK.*<\/family>/<family lang="ja">\n        <font weight="100" style="normal" index="0" postScriptName="NotoSansCJKjp-Thin">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="100.0" \/>\n        <\/font>\n        <font weight="300" style="normal" index="0" postScriptName="NotoSansCJKjp-Thin">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="300.0" \/>\n        <\/font>\n        <font weight="350" style="normal" index="0" postScriptName="NotoSansCJKjp-Thin">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="350.0" \/>\n        <\/font>\n        <font weight="400" style="normal" index="0" postScriptName="NotoSansCJKjp-Thin">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="400.0" \/>\n        <\/font>\n        <font weight="500" style="normal" index="0" postScriptName="NotoSansCJKjp-Thin">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="500.0" \/>\n        <\/font>\n        <font weight="700" style="normal" index="0" postScriptName="NotoSansCJKjp-Thin">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="700.0" \/>\n        <\/font>\n        <font weight="900" style="normal" index="0" postScriptName="NotoSansCJKjp-Thin">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="900.0" \/>\n        <\/font>\n\n        <font weight="200" style="normal" index="0" fallbackFor="serif" postScriptName="NotoSerifCJKjp-ExtraLight">NotoSerifCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="200.0" \/>\n        <\/font>\n        <font weight="300" style="normal" index="0" fallbackFor="serif" postScriptName="NotoSerifCJKjp-ExtraLight">NotoSerifCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="300.0" \/>\n        <\/font>\n        <font weight="400" style="normal" index="0" fallbackFor="serif" postScriptName="NotoSerifCJKjp-ExtraLight">NotoSerifCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="400.0" \/>\n        <\/font>\n        <font weight="500" style="normal" index="0" fallbackFor="serif" postScriptName="NotoSerifCJKjp-ExtraLight">NotoSerifCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="500.0" \/>\n        <\/font>\n        <font weight="600" style="normal" index="0" fallbackFor="serif" postScriptName="NotoSerifCJKjp-ExtraLight">NotoSerifCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="600.0" \/>\n        <\/font>\n        <font weight="700" style="normal" index="0" fallbackFor="serif" postScriptName="NotoSerifCJKjp-ExtraLight">NotoSerifCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="700.0" \/>\n        <\/font>\n        <font weight="900" style="normal" index="0" fallbackFor="serif" postScriptName="NotoSerifCJKjp-ExtraLight">NotoSerifCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="900.0" \/>\n        <\/font>\n    <\/family>/};
            ' $MODPATH$FILEPATH$FILE

            sed -i '
            /<family lang=\"ko\">/,/<\/family>/ {:a;N;/<\/family>/!ba;
            s/<family lang=\"ko\">.*Noto.*CJK.*<\/family>/<family lang="ko">\n        <font weight="100" style="normal" index="1" postScriptName="NotoSansCJKjp-Thin">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="100.0" \/>\n        <\/font>\n        <font weight="300" style="normal" index="1" postScriptName="NotoSansCJKjp-Thin">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="300.0" \/>\n        <\/font>\n        <font weight="350" style="normal" index="1" postScriptName="NotoSansCJKjp-Thin">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="350.0" \/>\n        <\/font>\n        <font weight="400" style="normal" index="1" postScriptName="NotoSansCJKjp-Thin">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="400.0" \/>\n        <\/font>\n        <font weight="500" style="normal" index="1" postScriptName="NotoSansCJKjp-Thin">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="500.0" \/>\n        <\/font>\n        <font weight="700" style="normal" index="1" postScriptName="NotoSansCJKjp-Thin">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="700.0" \/>\n        <\/font>\n        <font weight="900" style="normal" index="1" postScriptName="NotoSansCJKjp-Thin">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="900.0" \/>\n        <\/font>\n\n        <font weight="200" style="normal" index="1" fallbackFor="serif" postScriptName="NotoSerifCJKjp-ExtraLight">NotoSerifCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="200.0" \/>\n        <\/font>\n        <font weight="300" style="normal" index="1" fallbackFor="serif" postScriptName="NotoSerifCJKjp-ExtraLight">NotoSerifCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="300.0" \/>\n        <\/font>\n        <font weight="400" style="normal" index="1" fallbackFor="serif" postScriptName="NotoSerifCJKjp-ExtraLight">NotoSerifCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="400.0" \/>\n        <\/font>\n        <font weight="500" style="normal" index="1" fallbackFor="serif" postScriptName="NotoSerifCJKjp-ExtraLight">NotoSerifCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="500.0" \/>\n        <\/font>\n        <font weight="600" style="normal" index="1" fallbackFor="serif" postScriptName="NotoSerifCJKjp-ExtraLight">NotoSerifCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="600.0" \/>\n        <\/font>\n        <font weight="700" style="normal" index="1" fallbackFor="serif" postScriptName="NotoSerifCJKjp-ExtraLight">NotoSerifCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="700.0" \/>\n        <\/font>\n        <font weight="900" style="normal" index="1" fallbackFor="serif" postScriptName="NotoSerifCJKjp-ExtraLight">NotoSerifCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="900.0" \/>\n        <\/font>\n    <\/family>/};
            ' $MODPATH$FILEPATH$FILE
        elif [ "$API" -ge "28" ]; then
            sed -i '
            /<family lang=\"zh-Hans\">/,/<\/family>/ {:a;N;/<\/family>/!ba;
            s/<family lang=\"zh-Hans\">.*Noto.*CJK.*<\/family>/<family lang="zh-Hans">\n        <font weight="100" style="normal" index="2">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="100.0" \/>\n        <\/font>\n        <font weight="300" style="normal" index="2">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="300.0" \/>\n        <\/font>\n        <font weight="350" style="normal" index="2">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="350.0" \/>\n        <\/font>\n        <font weight="400" style="normal" index="2">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="400.0" \/>\n        <\/font>\n        <font weight="500" style="normal" index="2">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="500.0" \/>\n        <\/font>\n        <font weight="700" style="normal" index="2">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="700.0" \/>\n        <\/font>\n        <font weight="900" style="normal" index="2">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="900.0" \/>\n        <\/font>\n\n        <font weight="200" style="normal" index="2" fallbackFor="serif">NotoSerifCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="200.0" \/>\n        <\/font>\n        <font weight="300" style="normal" index="2" fallbackFor="serif">NotoSerifCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="300.0" \/>\n        <\/font>\n        <font weight="400" style="normal" index="2" fallbackFor="serif">NotoSerifCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="400.0" \/>\n        <\/font>\n        <font weight="500" style="normal" index="2" fallbackFor="serif">NotoSerifCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="500.0" \/>\n        <\/font>\n        <font weight="600" style="normal" index="2" fallbackFor="serif">NotoSerifCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="600.0" \/>\n        <\/font>\n        <font weight="700" style="normal" index="2" fallbackFor="serif">NotoSerifCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="700.0" \/>\n        <\/font>\n        <font weight="900" style="normal" index="2" fallbackFor="serif">NotoSerifCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="900.0" \/>\n        <\/font>\n    <\/family>/};
            ' $MODPATH$FILEPATH$FILE

            sed -i '
            /<family lang=\"zh-Hant\">/,/<\/family>/ {:a;N;/<\/family>/!ba;
            s/<family lang=\"zh-Hant\">.*Noto.*CJK.*<\/family>/<family lang="zh-Hant">\n        <font weight="100" style="normal" index="3">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="100.0" \/>\n        <\/font>\n        <font weight="300" style="normal" index="3">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="300.0" \/>\n        <\/font>\n        <font weight="350" style="normal" index="3">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="350.0" \/>\n        <\/font>\n        <font weight="400" style="normal" index="3">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="400.0" \/>\n        <\/font>\n        <font weight="500" style="normal" index="3">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="500.0" \/>\n        <\/font>\n        <font weight="700" style="normal" index="3">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="700.0" \/>\n        <\/font>\n        <font weight="900" style="normal" index="3">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="900.0" \/>\n        <\/font>\n\n        <font weight="200" style="normal" index="3" fallbackFor="serif">NotoSerifCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="200.0" \/>\n        <\/font>\n        <font weight="300" style="normal" index="3" fallbackFor="serif">NotoSerifCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="300.0" \/>\n        <\/font>\n        <font weight="400" style="normal" index="3" fallbackFor="serif">NotoSerifCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="400.0" \/>\n        <\/font>\n        <font weight="500" style="normal" index="3" fallbackFor="serif">NotoSerifCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="500.0" \/>\n        <\/font>\n        <font weight="600" style="normal" index="3" fallbackFor="serif">NotoSerifCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="600.0" \/>\n        <\/font>\n        <font weight="700" style="normal" index="3" fallbackFor="serif">NotoSerifCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="700.0" \/>\n        <\/font>\n        <font weight="900" style="normal" index="3" fallbackFor="serif">NotoSerifCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="900.0" \/>\n        <\/font>\n    <\/family>/};
            ' $MODPATH$FILEPATH$FILE

            sed -i '
            /<family lang=\"zh-Bopo\">/,/<\/family>/ {:a;N;/<\/family>/!ba;
            s/<family lang=\"zh-Bopo\">.*Noto.*CJK.*<\/family>/<family lang="zh-Bopo">\n        <font weight="100" style="normal" index="3">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="100.0" \/>\n        <\/font>\n        <font weight="300" style="normal" index="3">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="300.0" \/>\n        <\/font>\n        <font weight="350" style="normal" index="3">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="350.0" \/>\n        <\/font>\n        <font weight="400" style="normal" index="3">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="400.0" \/>\n        <\/font>\n        <font weight="500" style="normal" index="3">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="500.0" \/>\n        <\/font>\n        <font weight="700" style="normal" index="3">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="700.0" \/>\n        <\/font>\n        <font weight="900" style="normal" index="3">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="900.0" \/>\n        <\/font>\n\n        <font weight="200" style="normal" index="3" fallbackFor="serif">NotoSerifCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="200.0" \/>\n        <\/font>\n        <font weight="300" style="normal" index="3" fallbackFor="serif">NotoSerifCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="300.0" \/>\n        <\/font>\n        <font weight="400" style="normal" index="3" fallbackFor="serif">NotoSerifCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="400.0" \/>\n        <\/font>\n        <font weight="500" style="normal" index="3" fallbackFor="serif">NotoSerifCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="500.0" \/>\n        <\/font>\n        <font weight="600" style="normal" index="3" fallbackFor="serif">NotoSerifCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="600.0" \/>\n        <\/font>\n        <font weight="700" style="normal" index="3" fallbackFor="serif">NotoSerifCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="700.0" \/>\n        <\/font>\n        <font weight="900" style="normal" index="3" fallbackFor="serif">NotoSerifCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="900.0" \/>\n        <\/font>\n    <\/family>/};
            ' $MODPATH$FILEPATH$FILE

            sed -i '
            /<family lang=\"zh-Hant zh-Bopo\">/,/<\/family>/ {:a;N;/<\/family>/!ba;
            s/<family lang=\"zh-Hant zh-Bopo\">.*Noto.*CJK.*<\/family>/<family lang="zh-Hant zh-Bopo">\n        <font weight="100" style="normal" index="3">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="100.0" \/>\n        <\/font>\n        <font weight="300" style="normal" index="3">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="300.0" \/>\n        <\/font>\n        <font weight="350" style="normal" index="3">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="350.0" \/>\n        <\/font>\n        <font weight="400" style="normal" index="3">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="400.0" \/>\n        <\/font>\n        <font weight="500" style="normal" index="3">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="500.0" \/>\n        <\/font>\n        <font weight="700" style="normal" index="3">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="700.0" \/>\n        <\/font>\n        <font weight="900" style="normal" index="3">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="900.0" \/>\n        <\/font>\n\n        <font weight="200" style="normal" index="3" fallbackFor="serif">NotoSerifCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="200.0" \/>\n        <\/font>\n        <font weight="300" style="normal" index="3" fallbackFor="serif">NotoSerifCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="300.0" \/>\n        <\/font>\n        <font weight="400" style="normal" index="3" fallbackFor="serif">NotoSerifCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="400.0" \/>\n        <\/font>\n        <font weight="500" style="normal" index="3" fallbackFor="serif">NotoSerifCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="500.0" \/>\n        <\/font>\n        <font weight="600" style="normal" index="3" fallbackFor="serif">NotoSerifCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="600.0" \/>\n        <\/font>\n        <font weight="700" style="normal" index="3" fallbackFor="serif">NotoSerifCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="700.0" \/>\n        <\/font>\n        <font weight="900" style="normal" index="3" fallbackFor="serif">NotoSerifCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="900.0" \/>\n        <\/font>\n    <\/family>/};
            ' $MODPATH$FILEPATH$FILE

            sed -i '
            /<family lang=\"zh-Hant,zh-Bopo\">/,/<\/family>/ {:a;N;/<\/family>/!ba;
            s/<family lang=\"zh-Hant,zh-Bopo\">.*Noto.*CJK.*<\/family>/<family lang="zh-Hant,zh-Bopo">\n        <font weight="100" style="normal" index="3">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="100.0" \/>\n        <\/font>\n        <font weight="300" style="normal" index="3">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="300.0" \/>\n        <\/font>\n        <font weight="350" style="normal" index="3">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="350.0" \/>\n        <\/font>\n        <font weight="400" style="normal" index="3">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="400.0" \/>\n        <\/font>\n        <font weight="500" style="normal" index="3">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="500.0" \/>\n        <\/font>\n        <font weight="700" style="normal" index="3">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="700.0" \/>\n        <\/font>\n        <font weight="900" style="normal" index="3">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="900.0" \/>\n        <\/font>\n\n        <font weight="200" style="normal" index="3" fallbackFor="serif">NotoSerifCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="200.0" \/>\n        <\/font>\n        <font weight="300" style="normal" index="3" fallbackFor="serif">NotoSerifCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="300.0" \/>\n        <\/font>\n        <font weight="400" style="normal" index="3" fallbackFor="serif">NotoSerifCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="400.0" \/>\n        <\/font>\n        <font weight="500" style="normal" index="3" fallbackFor="serif">NotoSerifCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="500.0" \/>\n        <\/font>\n        <font weight="600" style="normal" index="3" fallbackFor="serif">NotoSerifCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="600.0" \/>\n        <\/font>\n        <font weight="700" style="normal" index="3" fallbackFor="serif">NotoSerifCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="700.0" \/>\n        <\/font>\n        <font weight="900" style="normal" index="3" fallbackFor="serif">NotoSerifCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="900.0" \/>\n        <\/font>\n    <\/family>/};
            ' $MODPATH$FILEPATH$FILE

            sed -i '
            /<family lang=\"ja\">/,/<\/family>/ {:a;N;/<\/family>/!ba;
            s/<family lang=\"ja\">.*Noto.*CJK.*<\/family>/<family lang="ja">\n        <font weight="100" style="normal" index="0">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="100.0" \/>\n        <\/font>\n        <font weight="300" style="normal" index="0">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="300.0" \/>\n        <\/font>\n        <font weight="350" style="normal" index="0">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="350.0" \/>\n        <\/font>\n        <font weight="400" style="normal" index="0">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="400.0" \/>\n        <\/font>\n        <font weight="500" style="normal" index="0">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="500.0" \/>\n        <\/font>\n        <font weight="700" style="normal" index="0">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="700.0" \/>\n        <\/font>\n        <font weight="900" style="normal" index="0">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="900.0" \/>\n        <\/font>\n\n        <font weight="200" style="normal" index="0" fallbackFor="serif">NotoSerifCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="200.0" \/>\n        <\/font>\n        <font weight="300" style="normal" index="0" fallbackFor="serif">NotoSerifCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="300.0" \/>\n        <\/font>\n        <font weight="400" style="normal" index="0" fallbackFor="serif">NotoSerifCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="400.0" \/>\n        <\/font>\n        <font weight="500" style="normal" index="0" fallbackFor="serif">NotoSerifCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="500.0" \/>\n        <\/font>\n        <font weight="600" style="normal" index="0" fallbackFor="serif">NotoSerifCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="600.0" \/>\n        <\/font>\n        <font weight="700" style="normal" index="0" fallbackFor="serif">NotoSerifCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="700.0" \/>\n        <\/font>\n        <font weight="900" style="normal" index="0" fallbackFor="serif">NotoSerifCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="900.0" \/>\n        <\/font>\n    <\/family>/};
            ' $MODPATH$FILEPATH$FILE

            sed -i '
            /<family lang=\"ko\">/,/<\/family>/ {:a;N;/<\/family>/!ba;
            s/<family lang=\"ko\">.*Noto.*CJK.*<\/family>/<family lang="ko">\n        <font weight="100" style="normal" index="1">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="100.0" \/>\n        <\/font>\n        <font weight="300" style="normal" index="1">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="300.0" \/>\n        <\/font>\n        <font weight="350" style="normal" index="1">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="350.0" \/>\n        <\/font>\n        <font weight="400" style="normal" index="1">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="400.0" \/>\n        <\/font>\n        <font weight="500" style="normal" index="1">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="500.0" \/>\n        <\/font>\n        <font weight="700" style="normal" index="1">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="700.0" \/>\n        <\/font>\n        <font weight="900" style="normal" index="1">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="900.0" \/>\n        <\/font>\n\n        <font weight="200" style="normal" index="1" fallbackFor="serif">NotoSerifCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="200.0" \/>\n        <\/font>\n        <font weight="300" style="normal" index="1" fallbackFor="serif">NotoSerifCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="300.0" \/>\n        <\/font>\n        <font weight="400" style="normal" index="1" fallbackFor="serif">NotoSerifCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="400.0" \/>\n        <\/font>\n        <font weight="500" style="normal" index="1" fallbackFor="serif">NotoSerifCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="500.0" \/>\n        <\/font>\n        <font weight="600" style="normal" index="1" fallbackFor="serif">NotoSerifCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="600.0" \/>\n        <\/font>\n        <font weight="700" style="normal" index="1" fallbackFor="serif">NotoSerifCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="700.0" \/>\n        <\/font>\n        <font weight="900" style="normal" index="1" fallbackFor="serif">NotoSerifCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="900.0" \/>\n        <\/font>\n    <\/family>/};
            ' $MODPATH$FILEPATH$FILE
        else
            if [ -f $MODPATH$FONTPATH$CHECKSUM ]; then
                ui_print "- Your Android is lower than 9.0(Pie) that doesn't support fallbackFor. Install $SANSNAME only."
                rm $MODPATH$FONTPATH$SERIFNAME
            fi

            ui_print "- Migrating $FILE"
            mkdir -p $MODPATH$FILEPATH
            cp -af $MIRRORPATH$FILEPATH$FILE $MODPATH$FILEPATH$FILE

            sed -i '
            /<family lang=\"zh-Hans\">/,/<\/family>/ {:a;N;/<\/family>/!ba;
            s/<family lang=\"zh-Hans\">.*Noto.*CJK.*<\/family>/<family lang="zh-Hans">\n        <font weight="100" style="normal" index="2">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="100.0" \/>\n        <\/font>\n        <font weight="300" style="normal" index="2">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="300.0" \/>\n        <\/font>\n        <font weight="350" style="normal" index="2">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="350.0" \/>\n        <\/font>\n        <font weight="400" style="normal" index="2">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="400.0" \/>\n        <\/font>\n        <font weight="500" style="normal" index="2">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="500.0" \/>\n        <\/font>\n        <font weight="700" style="normal" index="2">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="700.0" \/>\n        <\/font>\n        <font weight="900" style="normal" index="2">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="900.0" \/>\n        <\/font>\n    <\/family>/};
            ' $MODPATH$FILEPATH$FILE

            sed -i '
            /<family lang=\"zh-Hant\">/,/<\/family>/ {:a;N;/<\/family>/!ba;
            s/<family lang=\"zh-Hant\">.*Noto.*CJK.*<\/family>/<family lang="zh-Hant">\n        <font weight="100" style="normal" index="3">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="100.0" \/>\n        <\/font>\n        <font weight="300" style="normal" index="3">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="300.0" \/>\n        <\/font>\n        <font weight="350" style="normal" index="3">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="350.0" \/>\n        <\/font>\n        <font weight="400" style="normal" index="3">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="400.0" \/>\n        <\/font>\n        <font weight="500" style="normal" index="3">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="500.0" \/>\n        <\/font>\n        <font weight="700" style="normal" index="3">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="700.0" \/>\n        <\/font>\n        <font weight="900" style="normal" index="3">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="900.0" \/>\n        <\/font>\n    <\/family>/};
            ' $MODPATH$FILEPATH$FILE

            sed -i '
            /<family lang=\"zh-Bopo\">/,/<\/family>/ {:a;N;/<\/family>/!ba;
            s/<family lang=\"zh-Bopo\">.*Noto.*CJK.*<\/family>/<family lang="zh-Bopo">\n        <font weight="100" style="normal" index="3">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="100.0" \/>\n        <\/font>\n        <font weight="300" style="normal" index="3">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="300.0" \/>\n        <\/font>\n        <font weight="350" style="normal" index="3">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="350.0" \/>\n        <\/font>\n        <font weight="400" style="normal" index="3">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="400.0" \/>\n        <\/font>\n        <font weight="500" style="normal" index="3">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="500.0" \/>\n        <\/font>\n        <font weight="700" style="normal" index="3">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="700.0" \/>\n        <\/font>\n        <font weight="900" style="normal" index="3">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="900.0" \/>\n        <\/font>\n    <\/family>/};
            ' $MODPATH$FILEPATH$FILE

            sed -i '
            /<family lang=\"zh-Hant zh-Bopo\">/,/<\/family>/ {:a;N;/<\/family>/!ba;
            s/<family lang=\"zh-Hant zh-Bopo\">.*Noto.*CJK.*<\/family>/<family lang="zh-Hant zh-Bopo">\n        <font weight="100" style="normal" index="3">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="100.0" \/>\n        <\/font>\n        <font weight="300" style="normal" index="3">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="300.0" \/>\n        <\/font>\n        <font weight="350" style="normal" index="3">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="350.0" \/>\n        <\/font>\n        <font weight="400" style="normal" index="3">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="400.0" \/>\n        <\/font>\n        <font weight="500" style="normal" index="3">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="500.0" \/>\n        <\/font>\n        <font weight="700" style="normal" index="3">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="700.0" \/>\n        <\/font>\n        <font weight="900" style="normal" index="3">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="900.0" \/>\n        <\/font>\n    <\/family>/};
            ' $MODPATH$FILEPATH$FILE

            sed -i '
            /<family lang=\"zh-Hant,zh-Bopo\">/,/<\/family>/ {:a;N;/<\/family>/!ba;
            s/<family lang=\"zh-Hant,zh-Bopo\">.*Noto.*CJK.*<\/family>/<family lang="zh-Hant,zh-Bopo">\n        <font weight="100" style="normal" index="3">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="100.0" \/>\n        <\/font>\n        <font weight="300" style="normal" index="3">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="300.0" \/>\n        <\/font>\n        <font weight="350" style="normal" index="3">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="350.0" \/>\n        <\/font>\n        <font weight="400" style="normal" index="3">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="400.0" \/>\n        <\/font>\n        <font weight="500" style="normal" index="3">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="500.0" \/>\n        <\/font>\n        <font weight="700" style="normal" index="3">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="700.0" \/>\n        <\/font>\n        <font weight="900" style="normal" index="3">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="900.0" \/>\n        <\/font>\n    <\/family>/};
            ' $MODPATH$FILEPATH$FILE

            sed -i '
            /<family lang=\"ja\">/,/<\/family>/ {:a;N;/<\/family>/!ba;
            s/<family lang=\"ja\">.*Noto.*CJK.*<\/family>/<family lang="ja">\n        <font weight="100" style="normal" index="0">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="100.0" \/>\n        <\/font>\n        <font weight="300" style="normal" index="0">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="300.0" \/>\n        <\/font>\n        <font weight="350" style="normal" index="0">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="350.0" \/>\n        <\/font>\n        <font weight="400" style="normal" index="0">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="400.0" \/>\n        <\/font>\n        <font weight="500" style="normal" index="0">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="500.0" \/>\n        <\/font>\n        <font weight="700" style="normal" index="0">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="700.0" \/>\n        <\/font>\n        <font weight="900" style="normal" index="0">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="900.0" \/>\n        <\/font>\n    <\/family>/};
            ' $MODPATH$FILEPATH$FILE

            sed -i '
            /<family lang=\"ko\">/,/<\/family>/ {:a;N;/<\/family>/!ba;
            s/<family lang=\"ko\">.*Noto.*CJK.*<\/family>/<family lang="ko">\n        <font weight="100" style="normal" index="1">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="100.0" \/>\n        <\/font>\n        <font weight="300" style="normal" index="1">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="300.0" \/>\n        <\/font>\n        <font weight="350" style="normal" index="1">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="350.0" \/>\n        <\/font>\n        <font weight="400" style="normal" index="1">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="400.0" \/>\n        <\/font>\n        <font weight="500" style="normal" index="1">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="500.0" \/>\n        <\/font>\n        <font weight="700" style="normal" index="1">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="700.0" \/>\n        <\/font>\n        <font weight="900" style="normal" index="1">NotoSansCJK-VF-Android.otf.ttc\n            <axis tag="wght" stylevalue="900.0" \/>\n        <\/font>\n    <\/family>/};
            ' $MODPATH$FILEPATH$FILE
        fi
    fi
done

if [ "$TIMES" -lt "1" ]; then
    abort "! Migration FAILED. Or your Android version is lower than $MINVER. Nothing have done to your system."
fi
